In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("abalone.csv")

df.head()

  sex  length  diameter  height   whole  shucked  viscera  shell  rings
0   M   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1   M   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2   F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3   M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4   I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sex       4177 non-null   str
 1   length    4177 non-null   float64
 2   diameter  4177 non-null   float64
 3   height    4177 non-null   float64
 4   whole     4177 non-null   float64
 5   shucked   4177 non-null   float64
 6   viscera   4177 non-null   float64
 7   shell     4177 non-null   float64
 8   rings     4177 non-null   int64
dtypes: float64(7), int64(1), str(1)
memory usage: 297.9 KB

            length     diameter  ...        shell        rings
count  4177.000000  4177.000000  ...  4177.000000  4177.000000
mean      0.523992     0.407881  ...     0.238831     9.933684
std       0.120093     0.099240  ...     0.139203     3.224169
min       0.075000     0.055000  ...     0.001500     1.000000
25%       0.450000     0.350000  ...     0.130000     8.000000
50%       0.545000     0.425000  ...     0.234000     9.000000
75%       0.615000     0.480000  ...     0.329000    11.000000
max       0.815000     0.650000  ...     1.005000    29.000000

[8 rows x 8 columns]

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sex       4177 non-null   str
 1   length    4177 non-null   float64
 2   diameter  4177 non-null   float64
 3   height    4177 non-null   float64
 4   whole     4177 non-null   float64
 5   shucked   4177 non-null   float64
 6   viscera   4177 non-null   float64
 7   shell     4177 non-null   float64
 8   rings     4177 non-null   int64
dtypes: float64(7), int64(1), str(1)
memory usage: 297.9 KB

            length     diameter  ...        shell        rings
count  4177.000000  4177.000000  ...  4177.000000  4177.000000
mean      0.523992     0.407881  ...     0.238831     9.933684
std       0.120093     0.099240  ...     0.139203     3.224169
min       0.075000     0.055000  ...     0.001500     1.000000
25%       0.450000     0.350000  ...     0.130000     8.000000
50%       0.545000     0.425000  ...     0.234000     9.000000
75%       0.615000     0.480000  ...     0.329000    11.000000
max       0.815000     0.650000  ...     1.005000    29.000000

[8 rows x 8 columns]

In [6]:
[c for c in df.columns if "sex" in c.lower()]

['sex']

In [9]:
print(df.columns)
print(df.head())

Index(['sex', 'length', 'diameter', 'height', 'whole', 'shucked', 'viscera',
       'shell', 'rings'],
      dtype='str')
  sex  length  diameter  height   whole  shucked  viscera  shell  rings
0   M   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1   M   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2   F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3   M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4   I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [13]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [19]:
df.head()

  sex  length  diameter  height   whole  shucked  viscera  shell  rings
0   M   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1   M   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2   F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3   M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4   I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7

In [24]:
df.columns

Index(['sex', 'length', 'diameter', 'height', 'whole', 'shucked', 'viscera',
       'shell', 'rings'],
      dtype='str')

In [25]:
print(df.head())
print(df.columns)

  sex  length  diameter  height   whole  shucked  viscera  shell  rings
0   M   0.455     0.365   0.095  0.5140   0.2245   0.1010  0.150     15
1   M   0.350     0.265   0.090  0.2255   0.0995   0.0485  0.070      7
2   F   0.530     0.420   0.135  0.6770   0.2565   0.1415  0.210      9
3   M   0.440     0.365   0.125  0.5160   0.2155   0.1140  0.155     10
4   I   0.330     0.255   0.080  0.2050   0.0895   0.0395  0.055      7
Index(['sex', 'length', 'diameter', 'height', 'whole', 'shucked', 'viscera',
       'shell', 'rings'],
      dtype='str')

In [32]:
print(df.columns)

Index(['sex', 'length', 'diameter', 'height', 'whole', 'shucked', 'viscera',
       'shell', 'rings'],
      dtype='str')