In [1]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# =========================
# 2. Load Dataset
# =========================
# Update path if needed
df = pd.read_csv("crx.csv", header=None)

df.head()

   0      1     2   3   4   5   6   ...   9    10   11   12     13   14   15
0  a1     a2    s3  a4  a5  a6  a7  ...  a10  a11  a12  a13    a14  a15  a16
1   b  30.83     0   u   g   w   v  ...    t   01    f    g  00202    0    +
2   a  58.67  4.46   u   g   q   h  ...    t   06    f    g  00043  560    +
3   a  24.50   0.5   u   g   q   h  ...    f    0    f    g  00280  824    +
4   b  27.83  1.54   u   g   w   v  ...    t   05    t    g  00100    3    +

[5 rows x 16 columns]

In [6]:
df[cat_cols] = df[cat_cols].apply(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else "Unknown")
)

In [7]:
# =========================
# 4. Encode Categorical Features
# =========================
label_encoders = {}

for col in df.columns:
    if df[col].dtype == "object":
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le

df.head()

   0      1     2   3   4   5   6   ...   9    10   11   12     13   14   15
0  a1     a2    s3  a4  a5  a6  a7  ...  a10  a11  a12  a13    a14  a15  a16
1   b  30.83     0   u   g   w   v  ...    t   01    f    g  00202    0    +
2   a  58.67  4.46   u   g   q   h  ...    t   06    f    g  00043  560    +
3   a  24.50   0.5   u   g   q   h  ...    f    0    f    g  00280  824    +
4   b  27.83  1.54   u   g   w   v  ...    t   05    t    g  00100    3    +

[5 rows x 16 columns]

In [8]:
# =========================
# 5. Split Features & Target
# =========================
# Last column is target in CRX dataset
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [13]:
print(X_train.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
dtype: int64

In [17]:
X_train = X_train.apply(lambda col: col.astype('category').cat.codes if col.dtype == 'object' else col)