In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
df = pd.read_csv("DL-ATL.csv")

df.head()

         Date  ASM_Domestic  ...  RPM_Domestic  RPM_International
0  2002-10-01       2093602  ...       1527419           597313.0
1  2002-11-01       1999098  ...       1434927           566487.0
2  2002-12-01       2057104  ...       1615439           579713.0
3  2003-01-01       2068740  ...       1409105           536961.0
4  2003-02-01       1798127  ...       1307159           431583.0

[5 rows x 9 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(174, 9)
<class 'pandas.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      174 non-null    str
 1   ASM_Domestic              174 non-null    int64
 2   ASM_International         171 non-null    float64
 3   Flights_Domestic          174 non-null    int64
 4   Flights_International     171 non-null    float64
 5   Passengers_Domestic       174 non-null    int64
 6   Passengers_International  171 non-null    float64
 7   RPM_Domestic              174 non-null    int64
 8   RPM_International         171 non-null    float64
dtypes: float64(4), int64(4), str(1)
memory usage: 14.1 KB
None
       ASM_Domestic  ASM_International  ...  RPM_Domestic  RPM_International
count  1.740000e+02       1.710000e+02  ...  1.740000e+02       1.710000e+02
mean   2.029993e+06       1.137343e+06  ...  1.698567e+06       9.288944e+05
std    2.111990e+05       2.240688e+05  ...  2.220472e+05       2.119990e+05
min    1.546204e+06       6.332010e+05  ...  1.253961e+06       4.315830e+05
25%    1.870114e+06       9.857055e+05  ...  1.519817e+06       7.861625e+05
50%    2.034972e+06       1.148069e+06  ...  1.670642e+06       9.549960e+05
75%    2.175256e+06       1.292500e+06  ...  1.848650e+06       1.073334e+06
max    2.493453e+06       1.668447e+06  ...  2.227869e+06       1.348565e+06

[8 rows x 8 columns]
Date                        0
ASM_Domestic                0
ASM_International           3
Flights_Domestic            0
Flights_International       3
Passengers_Domestic         0
Passengers_International    3
RPM_Domestic                0
RPM_International           3
dtype: int64

In [4]:
target_column = "target"

In [5]:
df = df.dropna()

In [7]:
df[col] = le.fit_transform(df[col])

In [11]:
print(target_column in df.columns)

False

In [15]:
print(df.columns)

Index(['Date', 'ASM_Domestic', 'ASM_International', 'Flights_Domestic',
       'Flights_International', 'Passengers_Domestic',
       'Passengers_International', 'RPM_Domestic', 'RPM_International'],
      dtype='str')

In [17]:
print('rf_model' in globals())

False

In [18]:
dir()

['ExtraTreesClassifier',
 'In',
 'LabelEncoder',
 'Out',
 'RandomForestClassifier',
 '_',
 '_2',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy_score',
 'classification_report',
 'col',
 'confusion_matrix',
 'df',
 'exit',
 'get_ipython',
 'le',
 'np',
 'open',
 'pd',
 'quit',
 'target_column',
 'train_test_split']

In [22]:
print(df.head())
print(df.columns)

   Date  ASM_Domestic  ...  RPM_Domestic  RPM_International
0     0       2093602  ...       1527419           597313.0
1     1       1999098  ...       1434927           566487.0
2     2       2057104  ...       1615439           579713.0
3     3       2068740  ...       1409105           536961.0
4     4       1798127  ...       1307159           431583.0

[5 rows x 9 columns]
Index(['Date', 'ASM_Domestic', 'ASM_International', 'Flights_Domestic',
       'Flights_International', 'Passengers_Domestic',
       'Passengers_International', 'RPM_Domestic', 'RPM_International'],
      dtype='str')

In [27]:
df.head()

   Date  ASM_Domestic  ...  RPM_Domestic  RPM_International
0     0       2093602  ...       1527419           597313.0
1     1       1999098  ...       1434927           566487.0
2     2       2057104  ...       1615439           579713.0
3     3       2068740  ...       1409105           536961.0
4     4       1798127  ...       1307159           431583.0

[5 rows x 9 columns]

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      171 non-null    int64
 1   ASM_Domestic              171 non-null    int64
 2   ASM_International         171 non-null    float64
 3   Flights_Domestic          171 non-null    int64
 4   Flights_International     171 non-null    float64
 5   Passengers_Domestic       171 non-null    int64
 6   Passengers_International  171 non-null    float64
 7   RPM_Domestic              171 non-null    int64
 8   RPM_International         171 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 12.2 KB

In [29]:
df.columns

Index(['Date', 'ASM_Domestic', 'ASM_International', 'Flights_Domestic',
       'Flights_International', 'Passengers_Domestic',
       'Passengers_International', 'RPM_Domestic', 'RPM_International'],
      dtype='str')