In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor

from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv("gdp.csv")

df.head()

         date  total_expenditures  ...  producer_price_index  gross_domestic_product
0  2011-01-01              5766.7  ...                 192.7                 14881.3
1  2011-04-01              5870.8  ...                 203.1                 14989.6
2  2011-07-01              5802.6  ...                 204.6                 15021.1
3  2011-10-01              5812.9  ...                 201.1                 15190.3
4  2012-01-01              5765.7  ...                 200.7                 15291.0

[5 rows x 5 columns]

In [4]:
TARGET_COLUMN = "GDP"

if TARGET_COLUMN in df.columns:
    X = df.drop(columns=[TARGET_COLUMN])
    y = df[TARGET_COLUMN]
else:
    print("Target column not found. Available columns:", df.columns)

Target column not found. Available columns: Index(['date', 'total_expenditures', 'labor_force_pr', 'producer_price_index',
       'gross_domestic_product'],
      dtype='str')

In [10]:
print(df.columns)

Index(['date', 'total_expenditures', 'labor_force_pr', 'producer_price_index',
       'gross_domestic_product'],
      dtype='str')

In [15]:
print(df.columns)

Index(['date', 'total_expenditures', 'labor_force_pr', 'producer_price_index',
       'gross_domestic_product'],
      dtype='str')

In [18]:
df.columns

Index(['date', 'total_expenditures', 'labor_force_pr', 'producer_price_index',
       'gross_domestic_product'],
      dtype='str')

In [24]:
df.head()

         date  total_expenditures  ...  producer_price_index  gross_domestic_product
0  2011-01-01              5766.7  ...                 192.7                 14881.3
1  2011-04-01              5870.8  ...                 203.1                 14989.6
2  2011-07-01              5802.6  ...                 204.6                 15021.1
3  2011-10-01              5812.9  ...                 201.1                 15190.3
4  2012-01-01              5765.7  ...                 200.7                 15291.0

[5 rows x 5 columns]

In [27]:
df.head()
df.columns

Index(['date', 'total_expenditures', 'labor_force_pr', 'producer_price_index',
       'gross_domestic_product'],
      dtype='str')

In [31]:
print(df.columns)

Index(['date', 'total_expenditures', 'labor_force_pr', 'producer_price_index',
       'gross_domestic_product'],
      dtype='str')