In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
df = pd.read_csv("goalscorers.csv")

df.head()

         date  home_team away_team  ... minute own_goal  penalty
0  1916-07-02      Chile   Uruguay  ...   44.0    False    False
1  1916-07-02      Chile   Uruguay  ...   55.0    False    False
2  1916-07-02      Chile   Uruguay  ...   70.0    False    False
3  1916-07-02      Chile   Uruguay  ...   75.0    False    False
4  1916-07-06  Argentina     Chile  ...    2.0    False    False

[5 rows x 8 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(47601, 8)
<class 'pandas.DataFrame'>
RangeIndex: 47601 entries, 0 to 47600
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       47601 non-null  str
 1   home_team  47601 non-null  str
 2   away_team  47601 non-null  str
 3   team       47601 non-null  str
 4   scorer     47553 non-null  str
 5   minute     47345 non-null  float64
 6   own_goal   47601 non-null  bool
 7   penalty    47601 non-null  bool
dtypes: bool(2), float64(1), str(5)
memory usage: 4.5 MB
None
date           0
home_team      0
away_team      0
team           0
scorer        48
minute       256
own_goal       0
penalty        0
dtype: int64

In [4]:
df = df.fillna(0)

In [6]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'team', 'scorer', 'minute',
       'own_goal', 'penalty'],
      dtype='str')

In [10]:
df.columns

Index(['date', 'home_team', 'away_team', 'team', 'scorer', 'minute',
       'own_goal', 'penalty'],
      dtype='str')

In [11]:
df.head()
df.columns

Index(['date', 'home_team', 'away_team', 'team', 'scorer', 'minute',
       'own_goal', 'penalty'],
      dtype='str')

In [13]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'accuracy_score', 'classification_report', 'RandomForestClassifier', 'ExtraTreesClassifier', '_i2', 'df', '_2', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_i10', '_10', '_i11', '_11', '_i12', 'rf_model', '_i13'])

In [17]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'team', 'scorer', 'minute',
       'own_goal', 'penalty'],
      dtype='str')

In [18]:
print(df.columns)
df.head()

Index(['date', 'home_team', 'away_team', 'team', 'scorer', 'minute',
       'own_goal', 'penalty'],
      dtype='str')

         date  home_team away_team  ... minute own_goal  penalty
0  1916-07-02      Chile   Uruguay  ...   44.0    False    False
1  1916-07-02      Chile   Uruguay  ...   55.0    False    False
2  1916-07-02      Chile   Uruguay  ...   70.0    False    False
3  1916-07-02      Chile   Uruguay  ...   75.0    False    False
4  1916-07-06  Argentina     Chile  ...    2.0    False    False

[5 rows x 8 columns]

In [20]:
print(rf_model)

RandomForestClassifier(n_estimators=200, random_state=42)

In [23]:
et_model = ExtraTreesClassifier()