In [1]:
import pandas as pd
import numpy as np

# ML models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

# Clustering
from sklearn.cluster import KMeans

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

# Metrics
from sklearn.metrics import accuracy_score, classification_report

# Visualization
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("hosts.csv")

print(df.head())
print(df.info())

  redis1 KV 127.0.0.1 6379 0 0 1
0   l11 L1 127.0.0.1 10001 0 0 1
1   l12 L1 127.0.0.1 10101 1 0 1
2   l13 L1 127.0.0.1 10201 2 0 1
3   l21 L2 127.0.0.1 11001 0 0 1
4   l22 L2 127.0.0.1 11101 1 0 1
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 1 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   redis1 KV 127.0.0.1 6379 0 0 1  7 non-null      str
dtypes: str(1)
memory usage: 385.0 bytes
None

In [3]:
# Drop missing values
df = df.dropna()

# Example: remove duplicates
df = df.drop_duplicates()

print(df.shape)

(7, 1)

In [5]:
if text_column in df.columns:
    X_text = tfidf.fit_transform(df[text_column].astype(str)).toarray()
else:
    print(f"Column '{text_column}' not found. Available columns: {df.columns}")

Column 'description' not found. Available columns: Index(['redis1 KV 127.0.0.1 6379 0 0 1'], dtype='str')

In [7]:
print(df.columns)

Index(['redis1 KV 127.0.0.1 6379 0 0 1'], dtype='str')

In [8]:
for col in df.columns:
    print(f"'{col}'")

'redis1 KV 127.0.0.1 6379 0 0 1'

In [10]:
df.head()

  redis1 KV 127.0.0.1 6379 0 0 1
0   l11 L1 127.0.0.1 10001 0 0 1
1   l12 L1 127.0.0.1 10101 1 0 1
2   l13 L1 127.0.0.1 10201 2 0 1
3   l21 L2 127.0.0.1 11001 0 0 1
4   l22 L2 127.0.0.1 11101 1 0 1

In [13]:
(df.head())

  redis1 KV 127.0.0.1 6379 0 0 1
0   l11 L1 127.0.0.1 10001 0 0 1
1   l12 L1 127.0.0.1 10101 1 0 1
2   l13 L1 127.0.0.1 10201 2 0 1
3   l21 L2 127.0.0.1 11001 0 0 1
4   l22 L2 127.0.0.1 11101 1 0 1

In [18]:
print(df.columns)

Index(['redis1 KV 127.0.0.1 6379 0 0 1'], dtype='str')

In [20]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'RandomForestClassifier', 'ExtraTreesClassifier', 'KMeans', 'TfidfVectorizer', 'LabelEncoder', 'accuracy_score', 'classification_report', 'plt', '_i2', 'df', '_i3', '_i4', 'text_column', 'tfidf', '_i5', '_i6', 'label_column', 'le', '_i7', '_i8', 'col', '_i9', '_i10', '_10', '_i11', 'rf', '_i12', '_i13', '_13', '_i14', 'et', '_i15', '_i16', '_i17', '_i18', '_i19', 'kmeans', '_i20'])

In [23]:
print(hasattr(tfidf, "vocabulary_"))

False