In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("SNK - NeoGeo Pocket Color.csv")

df.head()

                                             Name EN                         Name CN
0     [BIOS] SNK NeoGeo Pocket Color (World) (En,Ja)  [BIOS] SNK NeoGeo Pocket Color
1  Bakumatsu Rouman Tokubetsu Hen - Gekka no Kens...                            月华剑士
2  Baseball Stars Color - Pocket Sports Series (W...                        明星棒球 彩色版
3             Big Bang Pro Wrestling (Japan) (En,Ja)                          职业摔角大赛
4   Bikkuriman 2000 - Viva! Pocket Festival! (Japan)              胜利者 2000 - 万岁！口袋节日

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(132, 2)
<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name EN  132 non-null    str
 1   Name CN  132 non-null    str
dtypes: str(2)
memory usage: 10.5 KB
None
Name EN    0
Name CN    0
dtype: int64

In [4]:
df = df.dropna()  # or you can use imputation if needed

In [6]:
if target_column in df.columns:
    X = df.drop(columns=[target_column])
    y = df[target_column]
else:
    print(f"{target_column} not found. Available columns: {df.columns.tolist()}")

target_column not found. Available columns: ['Name EN', 'Name CN']

In [12]:
X = df.copy()

In [17]:
print(df.head())
print(df.columns)

                                             Name EN                         Name CN
0     [BIOS] SNK NeoGeo Pocket Color (World) (En,Ja)  [BIOS] SNK NeoGeo Pocket Color
1  Bakumatsu Rouman Tokubetsu Hen - Gekka no Kens...                            月华剑士
2  Baseball Stars Color - Pocket Sports Series (W...                        明星棒球 彩色版
3             Big Bang Pro Wrestling (Japan) (En,Ja)                          职业摔角大赛
4   Bikkuriman 2000 - Viva! Pocket Festival! (Japan)              胜利者 2000 - 万岁！口袋节日
Index(['Name EN', 'Name CN'], dtype='str')

In [20]:
df.columns

Index(['Name EN', 'Name CN'], dtype='str')

In [21]:
df.head()

                                             Name EN                         Name CN
0     [BIOS] SNK NeoGeo Pocket Color (World) (En,Ja)  [BIOS] SNK NeoGeo Pocket Color
1  Bakumatsu Rouman Tokubetsu Hen - Gekka no Kens...                            月华剑士
2  Baseball Stars Color - Pocket Sports Series (W...                        明星棒球 彩色版
3             Big Bang Pro Wrestling (Japan) (En,Ja)                          职业摔角大赛
4   Bikkuriman 2000 - Viva! Pocket Festival! (Japan)              胜利者 2000 - 万岁！口袋节日

In [24]:
print(df.columns)

Index(['Name EN', 'Name CN'], dtype='str')

In [26]:
rf_model = RandomForestClassifier()  # this resets it