In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("prescriptions.csv")

df.head()

   Unnamed: 0 prescriber_id  num_opioid_prescriptions  num_prescriptions
0           0   BDRSDDB2&RA                         4                  7
1           1   3$N3WG4&BBO                        25                 28
2           2   S2NGGOGBRB4                         1                  1
3           3   S2NGGOGBRB4                        18                 22
4           4   NBORABOESOI                         1                  1

In [5]:
df = df.dropna()

In [6]:
print(df.columns)

Index(['Unnamed: 0', 'prescriber_id', 'num_opioid_prescriptions',
       'num_prescriptions'],
      dtype='str')

In [8]:
if text_column not in df.columns:
    print("Column not found:", text_column)

Column not found: review

In [11]:
import numpy as np

X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [13]:

df.head()

   Unnamed: 0 prescriber_id  num_opioid_prescriptions  num_prescriptions
0           0   BDRSDDB2&RA                         4                  7
1           1   3$N3WG4&BBO                        25                 28
2           2   S2NGGOGBRB4                         1                  1
3           3   S2NGGOGBRB4                        18                 22
4           4   NBORABOESOI                         1                  1

In [15]:
type(X)

numpy.ndarray

In [17]:
print("X shape:", X.shape)
print("Reduced shape:", reduced.shape)
print("DF shape:", df.shape)

X shape: (3, 2)
Reduced shape: (3, 2)
DF shape: (150, 4)

In [21]:
print(df.columns)

Index(['Unnamed: 0', 'prescriber_id', 'num_opioid_prescriptions',
       'num_prescriptions'],
      dtype='str')

In [24]:
print(df.columns)

Index(['Unnamed: 0', 'prescriber_id', 'num_opioid_prescriptions',
       'num_prescriptions'],
      dtype='str')

In [25]:
df.head()

   Unnamed: 0 prescriber_id  num_opioid_prescriptions  num_prescriptions
0           0   BDRSDDB2&RA                         4                  7
1           1   3$N3WG4&BBO                        25                 28
2           2   S2NGGOGBRB4                         1                  1
3           3   S2NGGOGBRB4                        18                 22
4           4   NBORABOESOI                         1                  1