In [2]:
# Core libraries
import pandas as pd
import numpy as np

# Visualization (optional but helpful)
import matplotlib.pyplot as plt
import seaborn as sns

# ML tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
# Load dataset
df = pd.read_csv("ps5.csv")

# Preview
df.head()

,url,id,publisherName,releaseDate,name,isAgeRestricted,activeCtaId,starRating/averageRating,starRating/totalRatingsCount
0,https://store.playstation.com/en-us/product/UP...,UP0101-PPSA19225_00-0159266583099383,"Konami Digital Entertainment, Inc.",2024-03-28T04:00:00Z,Felix the Cat,False,PREORDER:BUY_NOW:UP0101-PPSA19225_00-015926658...,5.00,1
1,https://store.playstation.com/en-us/product/UP...,UP2565-PPSA04379_00-0242096879154610,astragon Entertainment GmbH,2024-04-04T15:00:00Z,Construction Simulator - Gold Edition,False,PREORDER:BUY_NOW:UP2565-PPSA04379_00-024209687...,3.55,1526
2,https://store.playstation.com/en-us/product/UP...,UP4040-PPSA04721_00-HUNDREDHEROESDLX,505 Games,2024-04-21T13:00:00Z,Eiyuden Chronicle: Hundred Heroes - Digital De...,False,PREORDER:BUY_NOW:UP4040-PPSA04721_00-HUNDREDHE...,4.79,29
3,https://store.playstation.com/en-us/product/UP...,UP4040-PPSA04721_00-EIYUDENHEROESPS5,505 Games,2024-04-23T13:00:00Z,Eiyuden Chronicle: Hundred Heroes,False,PREORDER:BUY_NOW:UP4040-PPSA04721_00-EIYUDENHE...,4.79,29
4,https://store.playstation.com/en-us/product/UP...,UP9000-PPSA13196_00-STELLARBLADEDDE0,Sony Interactive Entertainment,2024-04-26T04:00:00Z,Stellar Blade™ Digital Deluxe Edition,False,PREORDER:BUY_NOW:UP9000-PPSA13196_00-STELLARBL...,0.00,0

In [4]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   url                           2001 non-null   str
 1   id                            2001 non-null   str
 2   publisherName                 2000 non-null   str
 3   releaseDate                   2001 non-null   str
 4   name                          2001 non-null   str
 5   isAgeRestricted               2001 non-null   bool
 6   activeCtaId                   2001 non-null   str
 7   starRating/averageRating      2001 non-null   float64
 8   starRating/totalRatingsCount  2001 non-null   int64
dtypes: bool(1), float64(1), int64(1), str(6)
memory usage: 623.5 KB

url                             0
id                              0
publisherName                   1
releaseDate                     0
name                            0
isAgeRestricted                 0
activeCtaId                     0
starRating/averageRating        0
starRating/totalRatingsCount    0
dtype: int64

In [5]:
# Drop duplicates
df = df.drop_duplicates()

# Handle missing values (example)
df = df.dropna()  # or use fillna()

In [7]:
from sklearn.preprocessing import LabelEncoder

for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [9]:
df.head()

,url,id,publisherName,releaseDate,name,isAgeRestricted,activeCtaId,starRating/averageRating,starRating/totalRatingsCount
0,150,150,247,926,597,False,1919,5.00,1
1,874,874,511,927,344,False,1946,3.55,1526
2,1089,1089,11,928,531,False,1953,4.79,29
3,1088,1088,11,929,530,False,1952,4.79,29
4,1992,1992,422,931,1488,False,1976,0.00,0

In [13]:
print(df.head())
print(df.columns.tolist())

                                                 url  \
0  https://store.playstation.com/en-us/product/UP...
1  https://store.playstation.com/en-us/product/UP...
2  https://store.playstation.com/en-us/product/UP...
3  https://store.playstation.com/en-us/product/UP...
4  https://store.playstation.com/en-us/product/UP...

                                     id                       publisherName  \
0  UP0101-PPSA19225_00-0159266583099383  Konami Digital Entertainment, Inc.
1  UP2565-PPSA04379_00-0242096879154610         astragon Entertainment GmbH
2  UP4040-PPSA04721_00-HUNDREDHEROESDLX                           505 Games
3  UP4040-PPSA04721_00-EIYUDENHEROESPS5                           505 Games
4  UP9000-PPSA13196_00-STELLARBLADEDDE0      Sony Interactive Entertainment

            releaseDate                                               name  \
0  2024-03-28T04:00:00Z                                      Felix the Cat
1  2024-04-04T15:00:00Z              Construction Simulator - Gold Edition
2  2024-04-21T13:00:00Z  Eiyuden Chronicle: Hundred Heroes - Digital De...
3  2024-04-23T13:00:00Z                  Eiyuden Chronicle: Hundred Heroes
4  2024-04-26T04:00:00Z              Stellar Blade™ Digital Deluxe Edition

   isAgeRestricted                                        activeCtaId  \
0            False  PREORDER:BUY_NOW:UP0101-PPSA19225_00-015926658...
1            False  PREORDER:BUY_NOW:UP2565-PPSA04379_00-024209687...
2            False  PREORDER:BUY_NOW:UP4040-PPSA04721_00-HUNDREDHE...
3            False  PREORDER:BUY_NOW:UP4040-PPSA04721_00-EIYUDENHE...
4            False  PREORDER:BUY_NOW:UP9000-PPSA13196_00-STELLARBL...

   starRating/averageRating  starRating/totalRatingsCount
0                      5.00                             1
1                      3.55                          1526
2                      4.79                            29
3                      4.79                            29
4                      0.00                             0
['url', 'id', 'publisherName', 'releaseDate', 'name', 'isAgeRestricted', 'activeCtaId', 'starRating/averageRating', 'starRating/totalRatingsCount']

In [17]:
print(df.columns)

Index(['url', 'id', 'publisherName', 'releaseDate', 'name', 'isAgeRestricted',
       'activeCtaId', 'starRating/averageRating',
       'starRating/totalRatingsCount'],
      dtype='str')

In [21]:
(print(df.head()))

                                                 url  \
0  https://store.playstation.com/en-us/product/UP...
1  https://store.playstation.com/en-us/product/UP...
2  https://store.playstation.com/en-us/product/UP...
3  https://store.playstation.com/en-us/product/UP...
4  https://store.playstation.com/en-us/product/UP...

                                     id                       publisherName  \
0  UP0101-PPSA19225_00-0159266583099383  Konami Digital Entertainment, Inc.
1  UP2565-PPSA04379_00-0242096879154610         astragon Entertainment GmbH
2  UP4040-PPSA04721_00-HUNDREDHEROESDLX                           505 Games
3  UP4040-PPSA04721_00-EIYUDENHEROESPS5                           505 Games
4  UP9000-PPSA13196_00-STELLARBLADEDDE0      Sony Interactive Entertainment

            releaseDate                                               name  \
0  2024-03-28T04:00:00Z                                      Felix the Cat
1  2024-04-04T15:00:00Z              Construction Simulator - Gold Edition
2  2024-04-21T13:00:00Z  Eiyuden Chronicle: Hundred Heroes - Digital De...
3  2024-04-23T13:00:00Z                  Eiyuden Chronicle: Hundred Heroes
4  2024-04-26T04:00:00Z              Stellar Blade™ Digital Deluxe Edition

   isAgeRestricted                                        activeCtaId  \
0            False  PREORDER:BUY_NOW:UP0101-PPSA19225_00-015926658...
1            False  PREORDER:BUY_NOW:UP2565-PPSA04379_00-024209687...
2            False  PREORDER:BUY_NOW:UP4040-PPSA04721_00-HUNDREDHE...
3            False  PREORDER:BUY_NOW:UP4040-PPSA04721_00-EIYUDENHE...
4            False  PREORDER:BUY_NOW:UP9000-PPSA13196_00-STELLARBL...

   starRating/averageRating  starRating/totalRatingsCount
0                      5.00                             1
1                      3.55                          1526
2                      4.79                            29
3                      4.79                            29
4                      0.00                             0

In [26]:
df.head()
df.columns

Index(['url', 'id', 'publisherName', 'releaseDate', 'name', 'isAgeRestricted',
       'activeCtaId', 'starRating/averageRating',
       'starRating/totalRatingsCount'],
      dtype='str')

In [30]:
print(df.columns)

Index(['url', 'id', 'publisherName', 'releaseDate', 'name', 'isAgeRestricted',
       'activeCtaId', 'starRating/averageRating',
       'starRating/totalRatingsCount'],
      dtype='str')

In [37]:
print(df.head())
print(df.columns)

                                                 url  \
0  https://store.playstation.com/en-us/product/UP...
1  https://store.playstation.com/en-us/product/UP...
2  https://store.playstation.com/en-us/product/UP...
3  https://store.playstation.com/en-us/product/UP...
4  https://store.playstation.com/en-us/product/UP...

                                     id                       publisherName  \
0  UP0101-PPSA19225_00-0159266583099383  Konami Digital Entertainment, Inc.
1  UP2565-PPSA04379_00-0242096879154610         astragon Entertainment GmbH
2  UP4040-PPSA04721_00-HUNDREDHEROESDLX                           505 Games
3  UP4040-PPSA04721_00-EIYUDENHEROESPS5                           505 Games
4  UP9000-PPSA13196_00-STELLARBLADEDDE0      Sony Interactive Entertainment

            releaseDate                                               name  \
0  2024-03-28T04:00:00Z                                      Felix the Cat
1  2024-04-04T15:00:00Z              Construction Simulator - Gold Edition
2  2024-04-21T13:00:00Z  Eiyuden Chronicle: Hundred Heroes - Digital De...
3  2024-04-23T13:00:00Z                  Eiyuden Chronicle: Hundred Heroes
4  2024-04-26T04:00:00Z              Stellar Blade™ Digital Deluxe Edition

   isAgeRestricted                                        activeCtaId  \
0            False  PREORDER:BUY_NOW:UP0101-PPSA19225_00-015926658...
1            False  PREORDER:BUY_NOW:UP2565-PPSA04379_00-024209687...
2            False  PREORDER:BUY_NOW:UP4040-PPSA04721_00-HUNDREDHE...
3            False  PREORDER:BUY_NOW:UP4040-PPSA04721_00-EIYUDENHE...
4            False  PREORDER:BUY_NOW:UP9000-PPSA13196_00-STELLARBL...

   starRating/averageRating  starRating/totalRatingsCount
0                      5.00                             1
1                      3.55                          1526
2                      4.79                            29
3                      4.79                            29
4                      0.00                             0
Index(['url', 'id', 'publisherName', 'releaseDate', 'name', 'isAgeRestricted',
       'activeCtaId', 'starRating/averageRating',
       'starRating/totalRatingsCount'],
      dtype='str')