In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
# Load dataset
df = pd.read_csv("soildataset.csv")

# View first rows
df.head()

   Id  Nitrogen  ...  Content of Phosphorous  Content of Potassium
0   1      3.67  ...                     Low                  High
1   2      3.99  ...                     Low                  High
2   3      4.31  ...                     Low                   Low
3   4      3.53  ...                     Low                  High
4   5      3.56  ...                     Low                  High

[5 rows x 7 columns]

In [3]:
# Dataset info
print(df.info())

# Check missing values
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      150 non-null    int64
 1   Nitrogen                150 non-null    float64
 2   Phosphorous             150 non-null    float64
 3   Potassium               150 non-null    float64
 4   Content of Nitrogen     150 non-null    str
 5   Content of Phosphorous  150 non-null    str
 6   Content of Potassium    150 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 10.3 KB
None
Id                        0
Nitrogen                  0
Phosphorous               0
Potassium                 0
Content of Nitrogen       0
Content of Phosphorous    0
Content of Potassium      0
dtype: int64

In [4]:
# Simple strategy: fill numeric NaNs with mean
df = df.fillna(df.mean(numeric_only=True))

In [7]:
df.columns = df.columns.str.strip()

In [9]:
if label_col in df.columns:
    X = df.drop(columns=[label_col])
    y = df[label_col]
else:
    print("Label column not found. Available columns:", df.columns)

Label column not found. Available columns: Index(['Id', 'Nitrogen', 'Phosphorous', 'Potassium', 'Content of Nitrogen',
       'Content of Phosphorous', 'Content of Potassium'],
      dtype='str')

In [13]:
df.head()
df.columns

Index(['Id', 'Nitrogen', 'Phosphorous', 'Potassium', 'Content of Nitrogen',
       'Content of Phosphorous', 'Content of Potassium'],
      dtype='str')

In [16]:
print(df.columns)

Index(['Id', 'Nitrogen', 'Phosphorous', 'Potassium', 'Content of Nitrogen',
       'Content of Phosphorous', 'Content of Potassium'],
      dtype='str')

In [17]:
df.head()

   Id  Nitrogen  ...  Content of Phosphorous  Content of Potassium
0   1      3.67  ...                     Low                  High
1   2      3.99  ...                     Low                  High
2   3      4.31  ...                     Low                   Low
3   4      3.53  ...                     Low                  High
4   5      3.56  ...                     Low                  High

[5 rows x 7 columns]

In [19]:
'y_test' in globals()

False

In [21]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'accuracy_score', 'classification_report', 'confusion_matrix', 'RandomForestClassifier', 'ExtraTreesClassifier', '_i2', 'df', '_2', '_i3', '_i4', '_i5', 'label_col', '_i6', '_i7', '_i8', '_i9', '_i10', '_i11', '_i12', '_i13', '_13', '_i14', 'rf_model', '_i15', '_i16', '_i17', '_17', '_i18', '_i19', '_19', '_i20', 'plt', '_i21'])