In [1]:
import pandas as pd
import numpy as np

# ML models
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.cluster import KMeans

# Metrics
from sklearn.metrics import accuracy_score, classification_report

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer

# Preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("stadiums.csv")

df.head()

   key_id  ...                               city_wikipedia_link
0       1  ...        https://en.wikipedia.org/wiki/Buenos_Aires
1       2  ...        https://en.wikipedia.org/wiki/Buenos_Aires
2       3  ...  https://en.wikipedia.org/wiki/Córdoba,_Argentina
3       4  ...       https://en.wikipedia.org/wiki/Mar_del_Plata
4       5  ...  https://en.wikipedia.org/wiki/Mendoza,_Argentina

[5 rows x 8 columns]

In [3]:
# Check missing values
print(df.isnull().sum())

# Fill missing values (simple strategy)
df = df.fillna("Unknown")

key_id                    0
stadium_id                0
stadium_name              0
city_name                 0
country_name              0
stadium_capacity          0
stadium_wikipedia_link    0
city_wikipedia_link       0
dtype: int64

In [5]:
for col in df.columns:
    print(col)

key_id
stadium_id
stadium_name
city_name
country_name
stadium_capacity
stadium_wikipedia_link
city_wikipedia_link

In [6]:
df.columns = df.columns.str.strip()

In [8]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = df.select_dtypes(include=['object', 'string']).columns

for col in categorical_cols:
    if col != text_column:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))

In [11]:
print(df.columns.tolist())

['key_id', 'stadium_id', 'stadium_name', 'city_name', 'country_name', 'stadium_capacity', 'stadium_wikipedia_link', 'city_wikipedia_link']

In [13]:
print(df.columns)

Index(['key_id', 'stadium_id', 'stadium_name', 'city_name', 'country_name',
       'stadium_capacity', 'stadium_wikipedia_link', 'city_wikipedia_link'],
      dtype='str')

In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load sample dataset
data = load_iris()
X = data.data
y = data.target

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [16]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [17]:
et = ExtraTreesClassifier(n_estimators=100, random_state=42)

et.fit(X_train, y_train)

y_pred_et = et.predict(X_test)

print("Extra Trees Accuracy:", accuracy_score(y_test, y_pred_et))
print(classification_report(y_test, y_pred_et))

Extra Trees Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [19]:
df.head()

   key_id  stadium_id  ...  stadium_wikipedia_link  city_wikipedia_link
0       1           0  ...                     100                   23
1       2           1  ...                      58                   23
2       3           2  ...                      57                   35
3       4           3  ...                      50                   98
4       5           4  ...                      55                  100

[5 rows x 8 columns]

In [20]:
print(len(df), len(X), len(clusters))

240 150 150

In [23]:
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(data)

feature_names = tfidf.get_feature_names_out()