In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("substitutions.csv")

df.head()

   key_id substitution_id tournament_id  ... match_period going_off coming_on
0       1          S-0001       WC-1970  ...  second half         1         0
1       2          S-0002       WC-1970  ...  second half         0         1
2       3          S-0003       WC-1970  ...  second half         1         0
3       4          S-0004       WC-1970  ...  second half         0         1
4       5          S-0005       WC-1970  ...  second half         1         0

[5 rows x 24 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(10222, 24)
<class 'pandas.DataFrame'>
RangeIndex: 10222 entries, 0 to 10221
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   key_id             10222 non-null  int64
 1   substitution_id    10222 non-null  str
 2   tournament_id      10222 non-null  str
 3   tournament_name    10222 non-null  str
 4   match_id           10222 non-null  str
 5   match_name         10222 non-null  str
 6   match_date         10222 non-null  str
 7   stage_name         10222 non-null  str
 8   group_name         10222 non-null  str
 9   team_id            10222 non-null  str
 10  team_name          10222 non-null  str
 11  team_code          10222 non-null  str
 12  home_team          10222 non-null  int64
 13  away_team          10222 non-null  int64
 14  player_id          10222 non-null  str
 15  family_name        10222 non-null  str
 16  given_name         10222 non-null  str
 17  shirt_number       10222 non-null  int64
 18  minute_label       10222 non-null  str
 19  minute_regulation  10222 non-null  int64
 20  minute_stoppage    10222 non-null  int64
 21  match_period       10222 non-null  str
 22  going_off          10222 non-null  int64
 23  coming_on          10222 non-null  int64
dtypes: int64(8), str(16)
memory usage: 3.3 MB
None
key_id               0
substitution_id      0
tournament_id        0
tournament_name      0
match_id             0
match_name           0
match_date           0
stage_name           0
group_name           0
team_id              0
team_name            0
team_code            0
home_team            0
away_team            0
player_id            0
family_name          0
given_name           0
shirt_number         0
minute_label         0
minute_regulation    0
minute_stoppage      0
match_period         0
going_off            0
coming_on            0
dtype: int64

In [4]:
df = df.dropna()  # simple approach; you can improve with imputation if needed

In [6]:
for col in df.select_dtypes(include=['object', 'string[python]']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

In [8]:
print("target" in df.columns)

False

In [9]:
print([col for col in df.columns])

['key_id', 'substitution_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'going_off', 'coming_on']

In [10]:
print(df.columns)

Index(['key_id', 'substitution_id', 'tournament_id', 'tournament_name',
       'match_id', 'match_name', 'match_date', 'stage_name', 'group_name',
       'team_id', 'team_name', 'team_code', 'home_team', 'away_team',
       'player_id', 'family_name', 'given_name', 'shirt_number',
       'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period',
       'going_off', 'coming_on'],
      dtype='str')

In [12]:
print(df.head())
print(df.columns.tolist())

   key_id  substitution_id  tournament_id  ...  match_period  going_off  coming_on
0       1                0              0  ...             6          1          0
1       2                1              0  ...             6          0          1
2       3                2              0  ...             6          1          0
3       4                3              0  ...             6          0          1
4       5                4              0  ...             6          1          0

[5 rows x 24 columns]
['key_id', 'substitution_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'going_off', 'coming_on']

In [16]:
df.head()
df.columns

Index(['key_id', 'substitution_id', 'tournament_id', 'tournament_name',
       'match_id', 'match_name', 'match_date', 'stage_name', 'group_name',
       'team_id', 'team_name', 'team_code', 'home_team', 'away_team',
       'player_id', 'family_name', 'given_name', 'shirt_number',
       'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period',
       'going_off', 'coming_on'],
      dtype='str')

In [19]:
df.head()

   key_id  substitution_id  tournament_id  ...  match_period  going_off  coming_on
0       1                0              0  ...             6          1          0
1       2                1              0  ...             6          0          1
2       3                2              0  ...             6          1          0
3       4                3              0  ...             6          0          1
4       5                4              0  ...             6          1          0

[5 rows x 24 columns]

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10222 entries, 0 to 10221
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   key_id             10222 non-null  int64
 1   substitution_id    10222 non-null  int64
 2   tournament_id      10222 non-null  int64
 3   tournament_name    10222 non-null  int64
 4   match_id           10222 non-null  int64
 5   match_name         10222 non-null  int64
 6   match_date         10222 non-null  int64
 7   stage_name         10222 non-null  int64
 8   group_name         10222 non-null  int64
 9   team_id            10222 non-null  int64
 10  team_name          10222 non-null  int64
 11  team_code          10222 non-null  int64
 12  home_team          10222 non-null  int64
 13  away_team          10222 non-null  int64
 14  player_id          10222 non-null  int64
 15  family_name        10222 non-null  int64
 16  given_name         10222 non-null  int64
 17  shirt_number       10222 non-null  int64
 18  minute_label       10222 non-null  int64
 19  minute_regulation  10222 non-null  int64
 20  minute_stoppage    10222 non-null  int64
 21  match_period       10222 non-null  int64
 22  going_off          10222 non-null  int64
 23  coming_on          10222 non-null  int64
dtypes: int64(24)
memory usage: 1.9 MB

In [22]:
print(df.columns)

Index(['key_id', 'substitution_id', 'tournament_id', 'tournament_name',
       'match_id', 'match_name', 'match_date', 'stage_name', 'group_name',
       'team_id', 'team_name', 'team_code', 'home_team', 'away_team',
       'player_id', 'family_name', 'given_name', 'shirt_number',
       'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period',
       'going_off', 'coming_on'],
      dtype='str')

In [27]:
print(df.head())

   key_id  substitution_id  tournament_id  ...  match_period  going_off  coming_on
0       1                0              0  ...             6          1          0
1       2                1              0  ...             6          0          1
2       3                2              0  ...             6          1          0
3       4                3              0  ...             6          0          1
4       5                4              0  ...             6          1          0

[5 rows x 24 columns]

In [29]:
print([name for name in globals() if "test" in name])

['train_test_split']